services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app                     # live code reload
      - static_volume:/app/static  # optional: persist static collected files
    ports:
      - "8000:8000"
    environment:
    - POSTGRES_DB=${POSTGRES_DB}         
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    - DEBUG=True 
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}    
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  static_volume:



  #can be done like this too to access env variables
  
#   version: '3.8'
# services:
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     volumes:
#       - .:/app
#       - static_volume:/app/static
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env  # All variables loaded from .env
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     env_file:
#       - .env  # Same file or create separate .env.db
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

# volumes:
#   pgdata:
  # static_volume:



