apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapadv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chapadv
  template:
    metadata:
      labels:
        app: chapadv
    spec:
      containers:
      - name: chapadv
        image: ceelo/chapadv:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: DJANGO_ENV
          valueFrom:
            configMapKeyRef:
              name: chapadv-config
              key: DJANGO_ENV
        - name: DJANGO_DEBUG
          valueFrom:
            configMapKeyRef:
              name: chapadv-config
              key: DJANGO_DEBUG
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: chapadv-config
              key: ALLOWED_HOSTS
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
            httpHeaders:
              - name: Host
                value: "localhost" 
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
            httpHeaders:
              - name: Host
                value: "localhost"
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc