apiVersion: v1
kind: Service
metadata:
  name: chapadv-service
spec:
  selector:
    app: chapadv-app
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432